stages:          # List of stages for jobs, and their order of execution
  - build
  - test

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - echo "Launching build..."
    - cargo build

test-code:
  stage: test
  script:
    - echo "Launching tests..."
    - cargo test